%ifndef _RFLAGS_INC
%define _RFLAGS_INC

%define CF         (1 <<  0)
%define RES1       (1 <<  1)
%define PF         (1 <<  2)
%define RES2       (1 <<  3)
%define AF         (1 <<  4)
%define RES3       (1 <<  5)
%define ZF         (1 <<  6)
%define SF         (1 <<  7)
%define TF         (1 <<  8)
%define IF         (1 <<  9)
%define DF         (1 << 10)
%define OF         (1 << 11)
%define IOPLBL     (1 << 12)
%define IOPLBH     (1 << 13)
%define NT         (1 << 14)
%define RESERVED1  (1 << 15)
%define RF         (1 << 16)
%define VM         (1 << 17)
%define AC         (1 << 18)
%define VIF        (1 << 19)
%define VIP        (1 << 20)
%define ID         (1 << 21)
%define RESERVED   (1 << 22)

%endif